#!/usr/bin/env bash

source_bin="`dirname $(realpath $0)`/bin"
default_bin="$HOME/bin"
bin_folders="/usr/local/bin $HOME/bin"

echo "Will try to link scripts in $bin_folders"
echo "$HOME/bin will be created if previous paths aren't writable, and it doesn't exist"

target_bin=${default_bin}

for folder in ${bin_folders}
do  

  if [ -d $folder ]
  then
    if [ ! -w $folder ]
    then
      #echo "folder $folder is not writable by current user"
      continue
    fi

    # bin found and writable
    target_bin=$folder
  fi
done

if [ "${folder}" == "${default_bin}" ]
then
  mkdir -p ${default_bin}
fi

echo "installing in $target_bin"
for b in "$source_bin"/*
do
  cmdname=`basename $b`
  if [ ! -f ${target_bin}/$cmdname ]
  then
    echo "linking $b to $target_bin"
    ln -s ${b} ${folder}
  else
    echo "link from $b to $target_bin already exists"
  fi
  
done
