version: 2.1
description: |
    A CircleCI Orb for installing custom Terraform utility scripts (tf-scripts)
    from a specified directory (typically 'bin') within the current repository
    into a directory in the system's PATH (typically /usr/local/bin)
    within a CircleCI build environment.
display:
    home_url: https://github.com/leecookson/tf-scripts
    source_url: https://github.com/leecookson/tf-scripts
orbs:
    terraform: circleci/terraform@3.6.0
commands:
    greet:
        description: |
            This command echos "Hello World" using file inclusion.
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - run:
                command: |
                    #!/bin/bash
                    # This example uses envsubst to support variable substitution in the string parameter type.
                    # https://circleci.com/docs/orbs-best-practices/#accepting-parameters-as-strings-or-environment-variables
                    TO=$(circleci env subst "${PARAM_TO}")
                    # If for any reason the TO variable is not set, default to "World"
                    echo "Hello ${TO:-World}!"
                environment:
                    PARAM_TO: <<parameters.to>>
                name: Hello Greeting
    install:
        description: 'Checks out the current repository and copies tf-scripts from ./bin to a target directory in the PATH. Note: If called by a job that also performs a checkout, this might result in a redundant checkout operation.'
        parameters:
            target_directory:
                default: /usr/local/bin
                description: The target directory (expected to be in PATH) where scripts will be copied (e.g., '/usr/local/bin').
                type: string
        steps:
            - terraform/install
            - run:
                command: |
                    set -e
                    echo "Cloning https://github.com/leecookson/tf-scripts into tf-scripts..."
                    git clone https://github.com/leecookson/tf-scripts tf-scripts
                    echo "Successfully cloned tf-scripts."
                name: Clone tf-scripts repository
            - run:
                command: |
                    set -e
                    ls -R tf-scripts
                    echo "Ensuring target directory '<< parameters.target_directory >>' exists..."
                    if ! sudo mkdir -p "<< parameters.target_directory >>"; then
                      echo "Error: Failed to create target directory '<< parameters.target_directory >>'."
                      exit 1
                    fi

                    echo "Copying scripts from 'tf-scripts/bin/'* to '<< parameters.target_directory >>/'..."
                    if ! sudo cp -f "tf-scripts/bin/"* "<< parameters.target_directory >>/"; then
                      echo "Error: Failed to copy scripts from 'tf-scripts/bin/' to '<< parameters.target_directory >>/'."
                      exit 1
                    fi

                    echo "Successfully copied scripts."
                    echo "Verifying copied scripts in '<< parameters.target_directory >>' (tf*.sh):"
                    ls -l "<< parameters.target_directory >>/tf"* || echo "Note: No tf* scripts found in '<< parameters.target_directory >>' or ls command failed."
                name: Copy tf-scripts from tf-scripts/bin to << parameters.target_directory >>
executors:
    default:
        description: |
            This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here. If you do not require an executor, you can simply delete this directory.
        docker:
            - image: cimg/node:<<parameters.tag>>
        parameters:
            tag:
                default: lts
                description: |
                    Pick a specific cimg/node image variant: https://hub.docker.com/r/cimg/node/tags
                type: string
jobs:
    hello:
        description: |
            Sample description
        executor: default
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - greet:
                to: << parameters.to >>
    install_scripts:
        description: Checks out the current repository and installs tf-scripts using the 'install_tf_scripts_to_path' command.
        docker:
            - image: cimg/base:stable
        parameters:
            checkout_path:
                default: .
                description: Path to checkout the repository to.
                type: string
            script_target_dir_in_path:
                default: /usr/local/bin
                description: The target directory (expected to be in PATH) to copy the scripts to (e.g., '/usr/local/bin').
                type: string
        steps:
            - checkout:
                path: << parameters.checkout_path >>
            - install:
                target_directory: << parameters.script_target_dir_in_path >>
examples:
    example:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                <orb-name>: <namespace>/<orb-name>@1.2.3
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/<job-name>
    install_and_run_script:
        description: Demonstrates checking out the tf-scripts repository, installing the scripts using this Orb, and then running one of the installed scripts in a subsequent job.
        usage:
            version: "2.1"
            orbs:
                tf_installer: leecookson/tf-scripts-orb@1.0.0
            workflows:
                main_workflow:
                    jobs:
                        - tf_installer/install_scripts:
                            name: setup_my_tf_scripts
                        - run_terraform_command:
                            docker:
                                - image: cimg/base:stable
                            requires:
                                - setup_my_tf_scripts
                            steps:
                                - checkout
                                - run:
                                    command: |
                                        echo "PATH is: $PATH"
                                        echo "Attempting to run tfplan.sh..."
                                        tfplan.sh # Assuming tfplan.sh is now in PATH and you are in a TF project directory
                                    name: Execute a tf-script

